### PR TITLE
broadcast audio when reconnect during guess & Response for ready unready and enterroom

### LINKED ISSUE #48: Implement comparison logic to verify whether the submitted answer matches the correct answer.

### PR DESCRIPTION
**Pull request by Zehao-Zhang**
closes #48 #49 #50 
1. Broadcast current audio to player who connect during guess phase
2. Player in the room can come back even it's full
3. Change the initial value from null to ""

### CODE REVIEW

**Review by zihanltesla — APPROVED** [review]
Great!

**Comment by zihanltesla** [comment]
closes #143 #142 #115

**Review by petertheprocess — APPROVED** [review]
Audio broadcast after reconnnection works.

**Comment by petertheprocess** [comment]
> closes #143 #142 #115

这样link也有用吗？

**Comment by zihanltesla** [comment]
好像没用,我手动关的 @petertheprocess

**Pull request merged**
